version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    ports:
      - "9000:9000"
    depends_on:
      - back-end-1
      - back-end-2

  back-end-1:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    ports:
      - "5252:5252"

  back-end-2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    ports:
      - "5253:5253"

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    container_name: softy-pinko-proxy-task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end-1
      - back-end-2